### ISSUE TITLE
In read_from_api, convert cast to character before row_bind

### ISSUE THREAD

**Issue by katemorkeski** [WHOIGit/ediutilities#13]

**Comment by joefutrelle** [comment]
The relevant code starts here, but `read_from_api` is a multi-purpose function that I think should be broken into smaller single-purpose functions, making it easier to address this and likely upcoming issues. If we don't do this we'll need to add more special cases in that function--and if we do it it will have some knock-on effects on our existing package workflows.

https://github.com/WHOIGit/ediutilities/blob/f863c931e80d1fe73af6e5beffac8a8d0cbf16df/R/edi-utilities.R#L180
