### ISSUE TITLE
request flexibility for project_insert

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/ediutilities#3]
so far we have three versions of parent_project.txt: just NES-LTER, NES-LTER + RAPID, and NES-LTER + OOI. It would be better to use different more descriptive filenames and declare which file to overwrite emlassemblyline project node

**Comment by joefutrelle** [comment]
Filename is hardcoded here https://github.com/WHOIGit/ediutilities/blob/1f9558d4f281d5f7777f8c507f94c7686e7d2d6f/R/edi-utilities.R#L113 

Change to argument
