### ISSUE TITLE
accommodate additional_info.txt file

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/ediutilities#6]
presently deletes the additional_info.txt file when running excel_to_template:
[INFO] other_info is FALSE; deleting additional_info.txt

**Comment by joefutrelle** [comment]
There are a few options for dealing with this:

* never, under any circumstances, delete `additional_info.txt`
* change the default of `other_info` to `TRUE`

I'm leaning towards the first, @sbeaulieu can you make this call?
